### ISSUE TITLE
Add server version and other info to health endpoint

### ISSUE THREAD

**Issue by btmorr** [btmorr/leifdb#48]
The health endpoint should include some diagnostic info, in addition to the status code. At a minimum, this should include the server version, but other info is fair game

**Comment by btmorr** [comment]
Note: this will probably require pulling the version string out of "version.sh" and making it readable/importable by both the source code and that script. This could be done several ways, including but not limited to:
- a top-level `package.json`
- a plaintext file that is read by the script using `cat` and is included in Go code during build
- a Go source file that is read by the version script (make sure it's possible to do this **before** building the binary, since it's an input to the `go build` step)
- another option that I haven't thought of

**Comment by kolharsam** [comment]
We could also add a `ldFlag` to the build process. How does that sound?

**Comment by btmorr** [comment]
Either of those options sounds good. I think I have a soft preference for the `env` solution, since then you wouldn't have to rebuild the binary if, for instance, you wanted to restart a server in debug without changing anything else.

**Comment by btmorr** [comment]
I think the `ldFlag` option makes sense for setting the version, since it's not something that should change after build
